on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CI: true
  NODE_VERSION: 16

defaults:
  run:
    shell: bash

name: sls-mentor-action
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for creating review comments
  
jobs:
  sls-mentor:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: aws
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::463151931555:role/github-action-role
          aws-region: eu-west-1
      - name: run sls-mentor
        id: run-sls-mentor
        run: |
          echo "SLS_MENTOR_RESULT<<EOF"$'\n'"$(npx sls-mentor@latest --level 1 --noFail)"$'\n'EOF >> "$GITHUB_OUTPUT"
        shell: bash
      - name: output
        env:
          SLS_MENTOR_RESULT: ${{ steps.run-sls-mentor.outputs.SLS_MENTOR_RESULT }} 
        run: echo "$SLS_MENTOR_RESULT"
